name: PermanentSet push and pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: Creating and setting venv
      run: sudo apt-get install python3 g++-12;
           python3 -m venv .venv;
           source .venv/bin/activate;
           conan profile detect --force
    - name: CMake release config
      run: conan install . --output-folder=build --build=missing;
           cd build/;
           cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    - name: CMake release build
      run: cmake --build build/tests/;
    - name: CMake release test
      run: cd build/tests/;
           ctest --output-on-failure  